---
title: "Visualization of RNA structure motifs"
author: "Salomon Marquez"
date: "`r Sys.Date()`"
output:
   html_document:
    code_folding: hide
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    toc_depth: 3
    number_sections: true
    self-contained: true
#output:
#   pdf_document:
#   latex_engine: xelatex  # o lualatex
#   keep_tex: yes
#   toc: yes
editor_options: 
  markdown: 
    wrap: 72
#editor_options: 
#  chunk_output_type: console
---


```{r setup, include=FALSE}
# Load knitr
library(knitr)

# Global R options
options(max.print = 50)
options(repos = c(CRAN = "https://cloud.r-project.org")) 

# Global chunk options
opts_chunk$set(
  echo = TRUE,     # show code
  cache = TRUE,    # caching
  prompt = FALSE,   # don’t show ">" in code
  tidy = TRUE,      # clean code formatting
  comment = NA,     # no extra comment symbols
  message = FALSE,  # hide package load messages
  warning = FALSE   # hide warnings
)

# Knitr rendering width
opts_knit$set(width = 100)
```


```{r, include=FALSE}
# Install and load modules and libraries 
install.packages("fmsb")

library(skimr)
library(scales)
library(ggplot2)
library(tidyr)
library(dplyr)
library(reshape2)
library(tidyverse)
library(dbplyr)
library(fmsb)
```

# Load dataset

```{r}    
# Specify a working directory
directory <- "/Volumes/DataWinBackup/00_MASTER UOC BIOINFORMATICA - TEMPORAL/TFM-UOC/RNAstructure/rna-structure-prediction"
setwd(directory)
list.files()
```

```{r}
# Read .csv file 
bpRNA_6_isoforms <- read.csv("bpRNA_st_stats_6_isoforms_all.csv", header=TRUE, row.names = 1, check.names = FALSE)
bpRNA_6_isoforms <- bpRNA_6_isoforms[7:12]
bpRNA_6_isoforms

# Read .csv file 
bpRNA_eocrc <- read.csv("bpRNA_st_stats_eocrc_all.csv", header=TRUE, row.names = 1, check.names = FALSE)
bpRNA_eocrc <- bpRNA_eocrc[7:12]
bpRNA_eocrc

# Read .csv file 
bpRNA_locrc <- read.csv("bpRNA_st_stats_locrc_all.csv", header=TRUE, row.names = 1, check.names = FALSE)
bpRNA_locrc <- bpRNA_locrc[7:12]
bpRNA_locrc
```
# Data summary

```{r}
# Summary of reports
summary(bpRNA_6_isoforms)
summary(bpRNA_eocrc)
summary(bpRNA_locrc)
```
# Motif visualization

```{r, heatmap_structural_elements_6_isoforms, fig.width=5.0, fig.height=4.0, dev="pdf", fig.path="figures/", fig.ext="pdf"}
# Heatmap plot of the 6 overlapped isoforms 
bpRNA_6_isoforms_long <- bpRNA_6_isoforms |>
  tibble::rownames_to_column("id") |>
  pivot_longer(
    -id,
    names_to = "feature",
    values_to = "count"
  )

ggplot(bpRNA_6_isoforms_long, aes(feature, id, fill = count)) +
  geom_tile(color = "white") +
  scale_fill_viridis_c(option = "A") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(
      angle = 45,
      hjust = 1,
      vjust = 1
    ),
    plot.title = element_text(hjust = 0.5)  # center title
  ) +
  labs(
    title = "Structural elements of overlapped isoforms",
    x = NULL,
    y = NULL,
    fill = "Count"
  )
```


```{r, heatmap_structural_elements_EOCRC, fig.width=5.0, fig.height=4.0, dev="pdf", fig.path="figures/", fig.ext="pdf"}
# Heatmap plot of EOCRC transcripts 
bpRNA_eocrc_long <- bpRNA_eocrc |>
  tibble::rownames_to_column("id") |>
  pivot_longer(
    -id,
    names_to = "feature",
    values_to = "count"
  )

ggplot(bpRNA_eocrc_long, aes(feature, id, fill = count)) +
  geom_tile(color = "white") +
  scale_fill_viridis_c(option = "A") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(
      angle = 45,
      hjust = 1,
      vjust = 1
    ),
    plot.title = element_text(hjust = 0.5)  # center title
  ) +
  labs(
    title = "Structural elements of EOCRC top isoforms",
    x = NULL,
    y = NULL,
    fill = "Count"
  )
```

```{r, heatmap_structural_elements_LOCRC, fig.width=5.0, fig.height=4.0, dev="pdf", fig.path="figures/", fig.ext="pdf"}
# Heatmap plot of LOCRC transcripts 
bpRNA_locrc_long <- bpRNA_locrc |>
  tibble::rownames_to_column("id") |>
  pivot_longer(
    -id,
    names_to = "feature",
    values_to = "count"
  )

ggplot(bpRNA_locrc_long, aes(feature, id, fill = count)) +
  geom_tile(color = "white") +
  scale_fill_viridis_c(option = "A") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(
      angle = 45,
      hjust = 1,
      vjust = 1
    ),
    plot.title = element_text(hjust = 0.5)  # center title
  ) +
  labs(
    title = "Structural elements of LOCRC top isoforms",
    x = NULL,
    y = NULL,
    fill = "Count"
  )
```

# R Session Information 

```{r, echo=FALSE}
# Session info
devtools::session_info()
```